SELECT TotalRevenue, ORDER_YEAR
FROM (
	SELECT SUM(TotalDue) AS TotalRevenue, ORDER_YEAR
	FROM (
		SELECT TotalDue, YEAR(OrderDate) AS ORDER_YEAR
		FROM Sales.SalesOrderHeader
		) AS ORDER_YEAR_TABLE
	GROUP BY ORDER_YEAR
	) AS TOTAL_SALES_REVENUE
WHERE ORDER_YEAR BETWEEN 2005 AND 2006


SELECT *
FROM Sales.SalesOrderHeader